### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by xday3** [Evi1Grey5/Evilginx-3-PHISHLET-LAB#8]
Facebook.yaml is not working. It did not capture any cookie or user and pass.

**Comment by Evi1Grey5** [comment]
I'll check it now and post the corrected version.
> Facebook.yaml is not working. It did not capture any cookie or user and pass.

**Comment by Evi1Grey5** [comment]
> Facebook.yaml is not working. It did not capture any cookie or user and pass.
![Screenshot_22](https://github.com/user-attachments/assets/5d688a19-a8ac-458e-915c-d28ad71f8df7)

It works perfectly, without any problems.

**Comment by fabrikano** [comment]
it has problem not work now

**Comment by Evi1Grey5** [comment]
> it has problem not work now

What exactly is the problem ?

**Comment by ghost-hub1** [comment]
Hello guys, 

Is there anyone that can help as to how to modify the http_proxy.go file in evilginx core cos when facebook sends 2fa auth to the device, it shows the location of the server hosting evilginx instead of retrieving the actual client's ip address but ua is good, issue is with the ip address somehow and after inspecting facebook network over and over, they dont use headers for ip address otherwise, this would have been very easy...

Please 🙏  anyone with help??? every other thing works so far just that when it is time to approve 2fa and you see another location?? that is definitely a problem.
